version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: clinic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prefinaltest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clinic_network

  mongodb:
    image: mongo:latest
    container_name: clinic_mongodb
    environment:
      MONGO_INITDB_DATABASE: prefinaltest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clinic_network

volumes:
  mysql_data:
  mongodb_data:

networks:
  clinic_network:
    driver: bridge